### ISSUE TITLE
nlp=True

### ISSUE THREAD

**Issue by Jinxz666** [StuPeter/AutoHome_spider#1]
感谢作者的分享，功能较全注释也很好理解。
在使用评论情感打分功能时，发现了一处小bug：AutoHomeSpider类中的analysis_Post函数中，初始化post['postSentiments']应写在内层循坏外，否则会报错；
关于自然语言处理，还有一点小建议：感觉部分打分有悖常识，产生偏差的主要原因可能是无效信息干扰了判断（e.g. 车主评价天气好导致打分高，但不是对车的直接评价），不知道snownlp这个包是否有类似信息拆分的函数，可以考虑先行过滤一遍。

**Comment by StuPeter** [comment]
感谢你的使用反馈，bug已经修复，关于NLP打分的问题，确实非常不妥，但是鉴于大部分小伙伴不会使用该功能，就不修改了哈😁
