### ISSUE TITLE
大佬您好，代码出现报错，请教一下

### ISSUE THREAD

**Issue by RX-00-Cat** [StuPeter/AutoHome_spider#3]
KeyError                                  Traceback (most recent call last)
<ipython-input-11-3262a2062ae4> in <module>
     50     #updateCarUrl()
     51     # 爬虫主程序
---> 52     main(pageIndex=1, BBSId=3411)

<ipython-input-11-3262a2062ae4> in main(pageIndex, BBSId)
     23     auto = AutoHomeSpider(nlp=True)
     24     # 选定论坛页，其中pageindex表示页码，bbsid表示车型代码
---> 25     topic = auto.analysis_forumPost(pageindex=pageIndex, bbsid=BBSId)
     26     # 循环爬取该页所有帖子
     27     for postUrl in topic['url']:

~\爬虫用\Autohome\AutoHomeSpiderClass.py in analysis_forumPost(self, pageindex, bbsid)
    125         }
    126         res = requests.get(self.forumApi, headers=self.headers, params=params, timeout=5)
--> 127         postList = res.json()['result']['list']
    128         topic = dict()
    129         topic['url'] = list()  # 帖子链接列表

KeyError: 'result'

**Comment by StuPeter** [comment]
感谢指出错误，因为汽车之家接口链接改变，所以当前项目无法正常运行。目前暂无重写的计划。再次感谢你对项目的关注！
